using System;
using Xunit;

namespace DotNetCoreShowcase.Tests
{
    // TODO: Remove. Visual Studio Autogenerated File. 

    public class TODOTest
    {
        [Fact]
        public void Test1()
        {

        }
    }
}
