using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;

namespace DotNetCoreShowcase.Controllers
{
    // TODO: Remove. Visual Studio Autogenerated File. 

    [ApiController]
    [Route("[controller]")]
    public class TODOController : ControllerBase
    {
        private static readonly string[] Summaries = new[]
        {
            "Freezing", "Bracing", "Chilly", "Cool", "Mild", "Warm", "Balmy", "Hot", "Sweltering", "Scorching"
        };

        private readonly ILogger<TODOController> _logger;

        public TODOController(ILogger<TODOController> logger)
        {
            _logger = logger;
        }

        [HttpGet]
        public IEnumerable<TODO> Get()
        {
            var rng = new Random();
            return Enumerable.Range(1, 5).Select(index => new TODO
            {
                Date = DateTime.Now.AddDays(index),
                TemperatureC = rng.Next(-20, 55),
                Summary = Summaries[rng.Next(Summaries.Length)]
            })
            .ToArray();
        }
    }
}
