using System;

namespace DotNetCoreShowcase
{
    // TODO: Remove. Visual Studio Autogenerated File.
    public class TODO
    {
        public DateTime Date { get; set; }

        public int TemperatureC { get; set; }

        public int TemperatureF => 32 + (int)(TemperatureC / 0.5556);

        public string Summary { get; set; }
    }
}
